# Generated by Django 4.2.1 on 2023-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_rename_doc_reciever_document_doc_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Doc_Files',
        ),
        migrations.AddField(
            model_name='document',
            name='Doc_Content',
            field=models.TextField(default=''),
        ),
    ]
