# Generated by Django 3.2.18 on 2023-04-17 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=10)),
                ('User_Rank', models.IntegerField()),
                ('User_Dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Emp.department')),
                ('User_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
