# Generated by Django 4.1 on 2023-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0003_employee_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dept_ID',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('PRD', 'Production')], max_length=3, primary_key=True, serialize=False),
        ),
    ]
