# Generated by Django 4.1 on 2023-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0004_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dept_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
