# Generated by Django 4.1 on 2023-05-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0005_alter_department_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_Rank',
            field=models.IntegerField(null=True),
        ),
    ]
