# Generated by Django 3.2.18 on 2023-04-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Document', '0001_initial'),
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLog_Time', models.DateTimeField()),
                ('CLog_Docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.document')),
                ('CLog_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cert_Path', models.CharField(max_length=100)),
                ('Cert_User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emp.employee')),
            ],
        ),
    ]
