# Generated by Django 3.2.18 on 2023-04-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certlog',
            name='CLog_Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
