# Generated by Django 3.2.18 on 2023-04-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicKey',
        ),
    ]
