# Generated by Django 3.2.18 on 2023-04-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Document', '0001_initial'),
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('Board_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Board_Create_Time', models.DateTimeField(auto_now=True)),
                ('Board_Title', models.CharField(max_length=50)),
                ('Board_Files', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Document.file')),
                ('Board_Writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Emp.employee')),
            ],
        ),
    ]
